"""empty message

Revision ID: d5338c0467d5
Revises: 
Create Date: 2018-08-21 16:11:57.685194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5338c0467d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_description', table_name='project')
    op.drop_index('ix_project_title', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_teammate_function', table_name='teammate')
    op.drop_index('ix_teammate_name', table_name='teammate')
    op.drop_table('teammate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teammate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('function', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teammate_name', 'teammate', ['name'], unique=False)
    op.create_index('ix_teammate_function', 'teammate', ['function'], unique=1)
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_title', 'project', ['title'], unique=1)
    op.create_index('ix_project_description', 'project', ['description'], unique=1)
    # ### end Alembic commands ###
